stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  

  evaluation:
    cmd: python src/deepClassifier/pipeline/stage_04_evaluation.py
    deps:
      - src/deepClassifier/pipeline/stage_04_evaluation.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false