
training_pipeline_config:
  pipeline_name: Quora_Artifacts
  artifact_dir: artifacts

data_ingestion_config:
  download_url: https://github.com/shivanshka/dataset/blob/main/quora_dummy_data_50k.zip?raw=true
  raw_data_dir: raw_data
  zipped_download_dir: zipped_data
  ingested_dir: ingested_data
  download_file_name: quora_data.zip

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessed_dir: preprocessed
  feature_eng_object_file_name: feat_eng.pkl
  preprocessed_object_file_name: preprocessed.pkl

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6

model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml

model_pusher_config:
  model_export_dir: saved_models
